.TH nhentai-dl 1 "Wed Jul 27 19:49:39 CEST 2016" "" "Linux User's Manual"

.SH NAME
\fBnhentai-dl\fP \- Downloader for nhentai.net and similar galleries.

.SH SYNOPSIS
.B nhentai-dl
.RI "[options]"
.RI "[gallery-url,...]"
.BR

.SH DESCRIPTION
\fBnhentai-dl\fP is a rather simple commandline downloader for nhentai.net and several other gallery sites (primarily Hentai/Porn ;)

.SH OPTIONS
.IP "\fB--help\fP / \fB-h\fP"
Shows a short usage message and lists available galleries.

.SH NOTES

.SH "SEE ALSO"
